# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            GitHub Training Hacktoberfest
tagline:          'Git through Hacktoberfest'
description:      'Daily tips, tricks, and insights from GitHub's Training team'
url:              https://brianamarie.github.io/wtd-hello/
baseurl:          /wtd-hello/

author:
  name:           'brianamarie'
  url:            https://twitter.com/brianamarie132

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/brianamarie/wtd-hello
